<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.6">
  <POU Name="Main" Id="{55dc8056-a83c-498b-9d09-689d30efbd92}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Main
VAR
	promise_TestSuite : Promise_TestSuite;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.Run();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>